blank_issues_enabled: true
contact_links:
  - name: å•é¡Œ
    url: https://github.com/Youzi9601/YZB-DiscordBot/issues
    about: ä½ å¯ä»¥é–‹å•ŸIssuesï¼Œæˆ‘å€‘å¾ˆå¿«å°±æœƒç‚ºæ‚¨æä¾›æ”¯æ´ï¼
  - name: ğŸ’¬ èŠå¤©
    url: https://discord.gg/Vq3F8DUNzf
    about: æƒ³è¦èˆ‡æ¢ç´¢æ›´å¤šæœ‰é—œæˆ‘çš„çš„äº‹æƒ…å—ï¼ŸåŠ å…¥æˆ‘å€‘çš„ä¼ºæœå™¨å§ï¼
